# Vectors

## Introduction

Vectors will be fundamental in our study of quantum computing. The most basic unit of computation in a quantum computer is a \emph{qubit}, which can be represented as a $2$-dimensional complex vector of length one. So understanding vectors will be foundational and necessary for most of what we will be doing in this book. Vectors can be thought of in many ways, one of the most basic is simply as an array of numbers, which we will often represent as a column of numbers called **column vectors**, but in some cases we will also need **row vectors**:


\begin{align} \text{Column Vector:} \ \begin{pmatrix}
a_1 \\ a_2 \\ \vdots \\ a_n
\end{pmatrix}, \quad \quad \text{Row Vector:} \ \begin{pmatrix}
a_1, & a_2, & \cdots, & a_n
\end{pmatrix} \end{align}

## Importing NumPy

For linear algebra, we need to make sure to import NumPy.

In [1]:
import numpy as np

## Row Vectors, Column Vectors, and Bra-Ket Notation

We can create a column vector and a row vector in Python:

In [2]:
# Create a vector as a row
row_vector = np.array([2-1j, 7j, -3])

# Create a vector as a column
column_vector = np.array([[2+1j],
                          [-5],
                          [2j]])

Row vectors in quantum mechanics are also called **bra-vectors**, and are denoted as follows:

\begin{align} \langle A| = \begin{pmatrix}
a_1, & a_2, \cdots, & a_n
\end{pmatrix} \end{align}

Column vectors are also called **ket-vectors** in quantum mechanics denoted as follows:

\begin{align} |B\rangle = \begin{pmatrix}
b_1 \\ b_2 \\ \vdots \\ b_n
\end{pmatrix} \end{align}

In general, if we have a column vector, i.e. a ket-vector:

\begin{align} |A\rangle = \begin{pmatrix}
a_1 \\ a_2 \\ \vdots \\ a_n
\end{pmatrix} \end{align}

the corresponding bra-vector:

\begin{align} \langle A| = \begin{pmatrix}
a_1^*, & a_2^*, & \cdots, & a_n^*
\end{pmatrix} \end{align}

is the **complex-conjugate transpose** of the ket-vector $|A\rangle$, and vice-versa. As an example, if we have the following ket-vector:


\begin{align} |A\rangle = \begin{pmatrix}
2+i \\ 1-3i
\end{pmatrix} \end{align}

then the corresponding bra-vector is:

\begin{align} \langle A| = \begin{pmatrix}
2-i, & 1+3i
\end{pmatrix} \end{align}

The notation $\langle A|$ and $|A\rangle$, for bra- and ket-vectors respectively, is a reference to \emph{inner products} denoted by brackets and we will discuss it more in the next section when we define inner product. As another example, we might want to have a pair of $2$-dimensional complex column vectors (meaning the entries are complex numbers):\\


\begin{align} |A \rangle = \begin{pmatrix}
2-i \\ 5
\end{pmatrix}, \quad \quad
|B \rangle = \begin{pmatrix}
7 \\ 3i
\end{pmatrix} \end{align}

Remember, $i^2 = -1$ and so $i = \sqrt{-1}$ is imaginary and complex numbers are always of the form $a + bi$. The corresponding bra-vectors would then be:

\begin{align} \langle A| = \begin{pmatrix}
2+i, & 5
\end{pmatrix}, \quad \quad \langle B| = \begin{pmatrix}
7, & -3i
\end{pmatrix} \end{align}

The $2$-dimensional vectors we have listed above are not quite the kind of vectors we will be using most often in quantum computing, but until we introduce the norm of a vector and explain what unit vectors are, let us focus on the basic operations we can perform on these vectors. We can always add two vector of the same dimension:

\begin{align} |A\rangle + |B\rangle = \begin{pmatrix}
2-i \\ 5
\end{pmatrix} + \begin{pmatrix}
7 \\ 3i
\end{pmatrix} =
\begin{pmatrix}
(2-i) + 7 \\ 5 + 3i
\end{pmatrix} =
\begin{pmatrix}
9-i \\ 5 + 3i
\end{pmatrix} \end{align}

In Python this can be done as follows:

In [3]:
ket_A = np.array([[2-1j],
                  [5]])
ket_B = np.array([[7],
                  [-3j]])
print(ket_A + ket_B)

[[9.-1.j]
 [5.-3.j]]


We can multiply bra-vectors and ket-vectors by scalars:

$ 3|A\rangle = 3 \begin{pmatrix} 2-i\\5 \end{pmatrix} = \begin{pmatrix} 6-3i\\15 \end{pmatrix} $

In [4]:
print(3*ket_A)

[[ 6.-3.j]
 [15.+0.j]]


Similarly for row vectors (bra-vectors):

$ 5\langle B| = 5 \begin{pmatrix} 7, & 3i \end{pmatrix}  = \begin{pmatrix} 35, & 15i \end{pmatrix}$

In [5]:
bra_B = np.array([[7, 3j]])
print(5*bra_B)

[[35. +0.j  0.+15.j]]


## Exercises

1. Define the following ket-vector as an array in Python:

\begin{align}
|\psi \rangle = \begin{pmatrix} 2, & 3i \end{pmatrix}
\end{align}

2. Define $|\psi \rangle$ from the previous problem as a (column) matrix and compute its Hermitian conjugate.
3. Define two ket vectors (column vectors) in Python:

\begin{align}
|A\rangle = \begin{pmatrix}
2 \\ 5-5j
\end{pmatrix}, \quad
|B\rangle = \begin{pmatrix}
2+3j \\ -3j
\end{pmatrix}
\end{align}

4. Compute $|A\rangle + |B\rangle$
5. Compute $3|A\rangle$.

In [8]:
w = np.array([[2], [-3j]])
w

array([[ 2.+0.j],
       [-0.-3.j]])

In [9]:
np.conj(w)

array([[ 2.-0.j],
       [-0.+3.j]])

In [11]:
A = np.array([[2], [5 -5j]])
B = np.array([[2+3j], [-3j]])

In [12]:
A + B

array([[4.+3.j],
       [5.-8.j]])

In [13]:
3*A

array([[ 6. +0.j],
       [15.-15.j]])