# Matrices

## Imports and Dependencies

We will primarily be using NumPy in this section.

In [1]:
import numpy as np

Matrices form the foundation for quantum gates, which are just operations on qubits that move the points representing states around the Bloch sphere. Matrices are also called operators or quantum gates in the context of quantum computing. They can operate on a single qubit, or on many qubits simultaneously. The matrix operators (or gates) we will be using most are known as *unitary operators* or *unitary matrices*. In this section we will discuss basic matrix algebra and define unitary matrices.

We have already seen two ways of realizing matrices in Python. Suppose we have the following $2 \times 2$ matrix

\begin{align}
M = \begin{pmatrix}
2-i & -3 \\
-5i & 2
\end{pmatrix}
\end{align}

We can define this matrix as a NumPy array, or as a matrix in Python.

In [2]:
M = np.array([[2-1j, -3],
              [-5j, 2]])

print(M)

[[ 2.-1.j -3.+0.j]
 [-0.-5.j  2.+0.j]]


Since we may want to compute Hermitian conjugates of matrices we will only be using the matrix data structure.

In [3]:
M = np.matrix([[2-1j, -3],
               [-5j, 2]])

print(M)

[[ 2.-1.j -3.+0.j]
 [-0.-5.j  2.+0.j]]


Remember, Hermitian conjugates are given by taking the conjugate transpose of the matrix. This means we compute the complex conjugate of each entry, and then transpose the matrix. Generally, the Hermitian conjugate is denoted by $M^{\dagger}$.

In [5]:
print(M.T)

[[ 2.-1.j -0.-5.j]
 [-3.+0.j  2.+0.j]]


In [6]:
print(np.conjugate(M.T))

[[ 2.+1.j -0.+5.j]
 [-3.-0.j  2.-0.j]]


In [7]:
print(M.H)

[[ 2.+1.j -0.+5.j]
 [-3.-0.j  2.-0.j]]


Let's have a look at another example of a Hermitian conjugate.

In [8]:
B = np.matrix([[1, -3j, 5, 2],
               [1-1j, 1, 3, 7j]])

print(B.H)

[[ 1.-0.j  1.+1.j]
 [-0.+3.j  1.-0.j]
 [ 5.-0.j  3.-0.j]
 [ 2.-0.j  0.-7.j]]


This is a $4 \times 2$ matrix which came from the $2 \times 4$ matrix $B$. Notice all of its entries have also been conjugated. We can also multiply matrices so long as the dimensions match appropriately. In particular, to multiply two matrices $A$ and $B$, the matrix must be an $n \times p$ matrix and the matrix $B$ must be a $p \times m$ matrix. The result is an $n \times m$ matrix. For example:

In [9]:
# Define a 3x2 matrix:
A = np.matrix([[2j, -5],
               [3-5j, 1],
               [5, 4j]])

# Define a 2x4 matrix:
B = np.matrix([[1, -3j, 5, 2],
               [1-1j, 1, 3, 7j]])

#Taking the product of a (3x2) and (2x4) matrix will give a 3x4 matrix:
np.dot(A, B)

matrix([[ -5. +7.j,   1. +0.j, -15.+10.j,   0.-31.j],
        [  4. -6.j, -14. -9.j,  18.-25.j,   6. -3.j],
        [  9. +4.j,   0.-11.j,  25.+12.j, -18. +0.j]])

If we are using the matrix definition instead of the array definition we can also multiply the two matrices as follows:

In [10]:
A*B

matrix([[ -5. +7.j,   1. +0.j, -15.+10.j,   0.-31.j],
        [  4. -6.j, -14. -9.j,  18.-25.j,   6. -3.j],
        [  9. +4.j,   0.-11.j,  25.+12.j, -18. +0.j]])

If we define the two matrices as arrays, this will not work and will return an error. We won't often be adding and subtracting matrices in the context of quantum computing but these operations are well defined for matrices of the same size. The Python code is exactly what you would expect it to be. Let's define two matrices of the same size.

In [11]:
M = np.matrix([[1, 2, 3],
               [1j, 2j, 3j]])

N = np.matrix([[2, 4, 6],
               [-2j, -4j, -6j]])

In [12]:
M+N

matrix([[3.+0.j, 6.+0.j, 9.+0.j],
        [0.-1.j, 0.-2.j, 0.-3.j]])

In [13]:
M-N

matrix([[-1.+0.j, -2.+0.j, -3.+0.j],
        [ 0.+3.j,  0.+6.j,  0.+9.j]])

We can also multiply matrices by scalars.

In [14]:
3*M

matrix([[3.+0.j, 6.+0.j, 9.+0.j],
        [0.+3.j, 0.+6.j, 0.+9.j]])

## Exercises

#### Define the following five matrices in Python:

\begin{align}
I = \begin{pmatrix} 1&0 \\ 0&1 \end{pmatrix}, \quad
X = \begin{pmatrix} 0&1 \\ 1&0 \end{pmatrix}, \quad
Y = \begin{pmatrix} 0&i \\ -i&0 \end{pmatrix}, \quad
Z = \begin{pmatrix} 1&0 \\ 0&-1 \end{pmatrix}, \quad
H = \frac{1}{\sqrt{2}} \begin{pmatrix} 1&1 \\ 1&-1 \end{pmatrix}
\end{align}

These are five of the most common single qubit gates used in quantum computing, and they will be used repeatedly.

In [17]:
I = np.matrix([[1, 0],[0, 1]])
X = np.matrix([[0, 1],[1, 0]])
Y = np.matrix([[0, 1j],[-1j, 0]])
Z = np.matrix([[1, 0],[0, -1]])
H = (1/np.sqrt(2))*np.matrix([[1, 1], [1, -1]])

#### Write Python code to compute the following matrix multiplications:

1. $XY$
2. $YX$
3. $YZ$
4. $ZY$
5. $HX$
6. $YH$
7. $XYZ$
8. $YZX$
9. $ZXY$
10. $XHY$

In [19]:
print(X*Y)
print(Y*X)
print(Y*Z)
print(Z*Y)
print(H*X)
print(Y*H)
print(X*Y*Z)
print(Y*Z*X)
print(Z*X*Y)
print(X*H*Y)

[[0.-1.j 0.+0.j]
 [0.+0.j 0.+1.j]]
[[0.+1.j 0.+0.j]
 [0.+0.j 0.-1.j]]
[[0.+0.j 0.-1.j]
 [0.-1.j 0.+0.j]]
[[0.+0.j 0.+1.j]
 [0.+1.j 0.+0.j]]
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[[0.+0.70710678j 0.-0.70710678j]
 [0.-0.70710678j 0.-0.70710678j]]
[[0.-1.j 0.+0.j]
 [0.+0.j 0.-1.j]]
[[0.-1.j 0.+0.j]
 [0.+0.j 0.-1.j]]
[[0.-1.j 0.+0.j]
 [0.+0.j 0.-1.j]]
[[0.+0.70710678j 0.+0.70710678j]
 [0.-0.70710678j 0.+0.70710678j]]
